### ISSUE TITLE
Video Camera crashes

### ISSUE THREAD

**Issue by prudhvirajkumar10** [mobapptuts/android_camera2_api_video_app#3]
When I run click the start video record button, the app crashes immediately. I'm using Nexus5 with API25

The entire logcat output is:

06-13 11:46:52.855 19998-19998/mobapptut.com.camera2videoimage E/MediaRecorder: prepare failed: -2147483648
06-13 11:46:52.855 19998-19998/mobapptut.com.camera2videoimage W/System.err: java.io.IOException: prepare failed.
06-13 11:46:52.855 19998-19998/mobapptut.com.camera2videoimage W/System.err:     at android.media.MediaRecorder._prepare(Native Method)
06-13 11:46:52.855 19998-19998/mobapptut.com.camera2videoimage W/System.err:     at android.media.MediaRecorder.prepare(MediaRecorder.java:848)
06-13 11:46:52.855 19998-19998/mobapptut.com.camera2videoimage W/System.err:     at mobapptut.com.camera2videoimage.Camera2VideoImageActivity.setupMediaRecorder(Camera2VideoImageActivity.java:711)
06-13 11:46:52.855 19998-19998/mobapptut.com.camera2videoimage W/System.err:     at mobapptut.com.camera2videoimage.Camera2VideoImageActivity.startRecord(Camera2VideoImageActivity.java:451)
06-13 11:46:52.855 19998-19998/mobapptut.com.camera2videoimage W/System.err:     at mobapptut.com.camera2videoimage.Camera2VideoImageActivity.checkWriteStoragePermission(Camera2VideoImageActivity.java:672)
06-13 11:46:52.855 19998-19998/mobapptut.com.camera2videoimage W/System.err:     at mobapptut.com.camera2videoimage.Camera2VideoImageActivity.access$1400(Camera2VideoImageActivity.java:54)
06-13 11:46:52.855 19998-19998/mobapptut.com.camera2videoimage W/System.err:     at mobapptut.com.camera2videoimage.Camera2VideoImageActivity$7.onClick(Camera2VideoImageActivity.java:311)
06-13 11:46:52.855 19998-19998/mobapptut.com.camera2videoimage W/System.err:     at android.view.View.performClick(View.java:5637)
06-13 11:46:52.855 19998-19998/mobapptut.com.camera2videoimage W/System.err:     at android.view.View$PerformClick.run(View.java:22429)
06-13 11:46:52.855 19998-19998/mobapptut.com.camera2videoimage W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)
06-13 11:46:52.856 19998-19998/mobapptut.com.camera2videoimage W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
06-13 11:46:52.856 19998-19998/mobapptut.com.camera2videoimage W/System.err:     at android.os.Looper.loop(Looper.java:154)
06-13 11:46:52.856 19998-19998/mobapptut.com.camera2videoimage W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6119)
06-13 11:46:52.856 19998-19998/mobapptut.com.camera2videoimage W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
06-13 11:46:52.856 19998-19998/mobapptut.com.camera2videoimage W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
06-13 11:46:52.856 19998-19998/mobapptut.com.camera2videoimage W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
06-13 11:46:52.856 19998-19998/mobapptut.com.camera2videoimage E/MediaRecorder: start called in an invalid state: 0
06-13 11:46:52.856 19998-19998/mobapptut.com.camera2videoimage D/AndroidRuntime: Shutting down VM
06-13 11:46:52.856 19998-19998/mobapptut.com.camera2videoimage E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                 Process: mobapptut.com.camera2videoimage, PID: 19998
                                                                                 java.lang.IllegalStateException
                                                                                     at android.media.MediaRecorder.start(Native Method)
                                                                                     at mobapptut.com.camera2videoimage.Camera2VideoImageActivity.checkWriteStoragePermission(Camera2VideoImageActivity.java:673)
                                                                                     at mobapptut.com.camera2videoimage.Camera2VideoImageActivity.access$1400(Camera2VideoImageActivity.java:54)
                                                                                     at mobapptut.com.camera2videoimage.Camera2VideoImageActivity$7.onClick(Camera2VideoImageActivity.java:311)
                                                                                     at android.view.View.performClick(View.java:5637)
                                                                                     at android.view.View$PerformClick.run(View.java:22429)
                                                                                     at android.os.Handler.handleCallback(Handler.java:751)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                     at android.os.Looper.loop(Looper.java:154)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
06-13 11:47:00.473 19998-19999/mobapptut.com.camera2videoimage I/art: Do partial code cache collection, code=27KB, data=30KB
06-13 11:47:00.473 19998-19999/mobapptut.com.camera2videoimage I/art: After code cache collection, code=27KB, data=30KB
06-13 11:47:00.473 19998-19999/mobapptut.com.camera2videoimage I/art: Increasing code cache capacity to 128KB

**Comment by Gaurav-pix** [comment]
You need to hold down the video recorder button to start recording in timeLapse which works and in case of regular video try playing with mMediaRecorder.setVideoSize()
